### ISSUE TITLE
Make progressive fallback URL

### ISSUE THREAD

**Issue by goatandsheep** [bitmovin/bitmovin-player-ui#225]
I want to have an mp4 fallback URL for when my HLS / Dash players don't work for the following errors:

* `SOURCE_COULD_NOT_LOAD_MANIFEST` (if I put a link with a typo)
* `SOURCE_NO_SUPPORTED_TECHNOLOGY` (if I don't even put an HLS / Dash link)

We could use the progressive as that fallback, but instead we get an error message.

**Comment by protyposis** [comment]
This issue is not related to the UI so I'm closing this. Please contact support@bitmovin.com for player issues.

Generally, there is no automatic fallback mechanism - this case is usually solved by listening to the errors and then loading an alternative source (the progressive fallback in your case).

**Comment by goatandsheep** [comment]
Sure, yes, but the UI doesn't allow for mp4.

**Comment by protyposis** [comment]
The UI is only an interface for playback control and not related to the playback engine of the player. It thus does neither "allow" nor "disallow" any media formats.

**Comment by goatandsheep** [comment]
@protyposis what's the link to the repo for the playback engine? I'd rather make a pull request.

**Comment by protyposis** [comment]
The player is closed source. Like said before, please contact support@bitmovin.com for player assistance or implement what I suggested above (or simply avoid invalid urls).

**Comment by goatandsheep** [comment]
thank you for your help @protyposis
