### ISSUE TITLE
Multiple taps required to start live stream (iOS, Android)

### ISSUE THREAD

**Issue by MattDoddsMI** [bitmovin/bitmovin-player-ui#31]
Using Player Version 7.2.2 and UI Version 2.7.1, I'm seeing the same behaviour as reported in issue #10 - on iOS (10.3.2, 10.3.3beta, 9.3.2) I have to tap at least twice, sometimes three times to initiate playback of a live stream.

Android / Chrome 59.0.3071.125 seems to have a similar issue.

It's as if one tap on the big play button brings up the UI, another tap sends the UI away, and the third starts playback.

Test stream is here, using latest player and default UI: http://swisscomstream.ch/player/bitmovin7latest_AD.php

**Comment by protyposis** [comment]
Thanks for reporting. This problem is twofold:

 - The impression that you get that you need to press play multiple times is because in player 7.2, the `ON_PLAY` event is delayed until the actual playback starts. So when you press play, the play button does not disappear immediately but only after everything is loaded and playback actually started. If there is a long delay, this looks like playback does not start where in reality it still does but is not visually represented. This concerns all platforms (Android & iOS), but is the sole issue on Android. As said this is a player issue (not UI) in 7.2, which we are aware of and leads to a bad user experience, and it will be fixed in 7.3.
 - On iOS, there's the additional problem that the invalid ad tag that is specified in the advertisement config of the test page is not correctly skipped. This can be solved on your side by removing the invalid tag, and will also be fixed in player 7.3.

**Comment by MattDoddsMI** [comment]
Ahh, thanks Mario. I'll feed this back to our end-client. The sample page is from them but we experience similar effects in our own product (we don't use the ad tag though).

One related question - is the act of tapping the huge play button exactly the same as the small play button in the control bar? The player is still waiting for the ON_PLAY event in the same way?

**Comment by protyposis** [comment]
The huge play button has additional logic to toggle fullscreen on double tab, but related to `ON_PLAY` its exactly the same behavior.

**Comment by protyposis** [comment]
Closing this. Please reopen if you feel this issue is still unresolved.
