### ISSUE TITLE
seekbar on safari in livestream is visible

### ISSUE THREAD

**Issue by dirkro** [bitmovin/bitmovin-player-ui#355]
**Browser:** Safari
**OS:** Mac OS
**Device:** Mac
**SDK Version:** 8.49.0

**URL:** https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Fron-i.akamaihd.net%2Fhls%2Flive%2F523496%2Fron%2Fmaster.m3u8

**Steps to reproduce:** 
1. Open Stream URL with Safari
2. Seekbar is visible
---
1. Open Stream URL with Chrome
2. Seekbar is invisible

## Description

**Current behaviour:** 
- when watching a livestream without timeshift the seekbar is visible in the safari browser
- in google chrome the seekbar is invisible (expected behavior)

**Expected behaviour:**
the seekbar is invisible in safari browser and google chrome browser

**Comment by jamesdavidholding** [comment]
Hi @dirkro 

We will be closing the ‘Issues’ tab for this Repo this week and all issues within it will be closed. If this issue is still affecting you, please re-raise it through the Bitmovin Support Dashboard, where we will be happy to pick it up. 

This change improves our responses to you, as the support team is currently not monitoring GitHub repro support sections.

Many thanks,

James - Support
