### ISSUE TITLE
Overlapping Subtitle Queues break Subtitles in Safari 

### ISSUE THREAD

**Issue by ASpwalters** [bitmovin/bitmovin-player-ui#509]
### Bug
In Safari, when there are overlapping subtitle queues it causes subtitles to start acting erratically. Tested in other browsers and it seemed to work as expected.

### Expectation
Subtitles should continue to work per the WEBVTT spec which allows for overlapping subtitles.

### How to Reproduce
It's reproducable with the Bitmovin test player at http://bitmovin.com/hls-mpeg-dash-test-player/ which is on version 8.100.0 at the time of this report.

If you navigate to the 15:33 mark of this video in the Safari browser, you will observe the bug.
https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Fmedia.angelstudios.com%2Fcopied-content%2Fmasters%2F94d6ca81-813e-49d8-ab52-e83a275fcc14.m3u8

This is the same video but without the overlap and it works as expected.
https://bitmovin.com/demos/stream-test?format=hls&manifest=https%3A%2F%2Fmedia.angelstudios.com%2Fcopied-content%2Fmasters%2F729dc75e-03fd-491d-9917-607ff901ca1a.m3u8

**Comment by jamesdavidholding** [comment]
Hi @dirkro 

Hi Patrick,

We will be closing the ‘Issues’ tab for this Repo this week and all issues within it will be closed. If this issue is still affecting you, please re-raise it through the Bitmovin Support Dashboard, where we will be happy to pick it up. 

This change improves our responses to you, as the support team is currently not monitoring GitHub repro support sections.

Many thanks,

James - Support
